### ISSUE TITLE
Cambio en tabla de factores para cálculo de la prima

### ISSUE THREAD

**Issue by cmonsalvec** [JorgePaladines/jenkins_taller_is2#2]
Estimados,

De acuerdo a las estadísticas del 2019 hemos comprobado que la siniestralidad de conductores de 65 años de edad o más ha aumentado. Por tal razón el directorio de nuestra empresa ha decidido modificar para este rango de edad el número de puntos que puede perder en su licencia de conducir. El directorio ha aprobado que ese número de puntos pase de 5 a 4.

Por favor realizar los cambios en el sistema para que esta nueva disposición del directorio pueda entrar en funcionamiento.

**Comment by JorgePaladines** [comment]
**ETAPA 2: REPRODUCIR EL PROBLEMA**

Se muestra que efectivamente, el cálculo de la prima para la edad de 65 o más permite la reducción de hasta 5 puntos.

![image](https://user-images.githubusercontent.com/25188838/72222775-72dfd800-3536-11ea-89f2-99c37b004c91.png)

**Comment by cmonsalvec** [comment]
Recordar que el ticket debe ser atendido por todo el equipo. Cada miembro puede hacerse cargo de 1 o más etapas del mantenimiento, pero cada uno al menos debe tener una etapa a cargo.

Además, también de alguna manera etiquetar cada paso para conocer en que etapa se está. Con lo hecho toca interpretar el conocer en que etapa de mantenimiento se encuentra.

**Comment by mianmuri1991** [comment]
**ETAPA 5: ANÁLISIS DE IMPACTO DEL INCIDENTE**

El análisis de impacto se ha realizado desde un punto de vista cuantitativo, identificando qué elementos están involucrados en la petición de cambio solicitada. Se ha realizado un cambio en dos de las funciones del modulo CalcPrima.java llamadas rangoEdad() y aplicaReduccion(), la primera permite obtener el máximo valor permitido de puntos a reducir para un determinado rango de edad mientras que la segunda tiene varios switch cases y uno de ellos pertenece a los conductores de 65 años o más; el mismo se ha cambiado para que los puntos permitidos sean menores o iguales a 4.. Estas funciones se utilizan en otra llamada calcularPrima() en la cual no hubo la necesidad de realizar modificaciones oportunas; sin embargo el valor devuelto por ella si depende de los valores enviados por rangoEdad() y aplicaReduccion(), por esta razón el impacto del incidente es **medio** sobre la función apenas mencionada. La función calcularPrima() a su vez es utilizada por otra cuyo nombre es retornarPrima(), en la misma no hubo necesidad de realizar modificaciones pero sus valores devueltos también dependen implícitamente de rangoEdad() y aplicaReduccion(), por ello el impacto del incidente también es **medio** para esta funcionalidad. La función retornarPrima() se utiliza en los módulos MainPrima.java, PrimaTest.java (pruebas de sistema con JUnit) y AutomatedPrimaTests.java (pruebas de aceptación con Cucumber). En todos ellos tampoco hubo la necesidad de hacer cambios en sus funcionalidades, pero nuevamente los valores devueltos por rangoEdad() y aplicaReduccion() representan la base de las operaciones posteriores en las otras funciones; por ello los impactos del incidente se consideran de nivel **medio** en ellas también. De manera general, el impacto que el incidente ha producido ha sido de nivel **alto** solo para el modulo CalcPrima.java en sus funciones rangoEdad() y aplicaReduccion() dado que ese cambio altera los valores calculados para las personas con 65 años de edad o mas, sin embargo las modificaciones solo se realizan en dichas funciones puesto que todas las que dependen de ellas solo reciben los valores enviados por las mismas y los procesan. Todas estas funciones dependen de las modificadas en las cuales los cambios representaron un impacto muy **alto** para las mismas, en las funciones dependientes de ellas no hubieron cambios a realizar en la codificación, pero si hay una incidencia implícita por parte de las funciones rangoEdad() y aplicaReduccion() por ellos sus impactos se consideran de nivel **medio**.

**Comment by JorgePaladines** [comment]
**ETAPA 6: TRABAJAR EN LA SOLUCIÓN DEL INCIDENTE**

La función aplicaReduccion() calcula los puntos perdidos, y en base al índice de edad el cual entra por argumento, se retorna un valor booleano que indica si superó el máximo de puntos permitidos.

![image](https://user-images.githubusercontent.com/25188838/72488359-bceae700-37de-11ea-8aeb-9814c43cdbf2.png)

En el switch case, el "case 4" de la línea 95 pertenece a los conductores de 65 años o más, y se ha cambiado a que los puntos sean permitidos a ser menores o iguales a 4.

**Comment by dcmonten** [comment]
# Etapa 7
## **Pruebas de sistema**
### Clases de equivalencia
Edad - E
Puntos - P
Prima - Pr
#### Edad
CE1: E es un número entero
CE2: E no es un número entero
CE3: E < 18
CE4: E >= 18 y E <25 
CE5: E >= 25 y E < 35
CE6: E >= 35 y E < 45
CE7: E >= 45 y E < 65
CE8: E >=65 y E <=90
CE9: E > 90
##### Puntos
CE10: P es un número entero
CE11: P no es un número entero
CE12: P < 1
CE13: P > 30
CE14: 1<=P<=30
##### Salidas posibles
CE15: E >= 18 y E <25 y P >=29 y P<=30 --> Pr = 1350
CE16: E >= 25 y E < 35 y P >=27 y P<=30 --> Pr = 850
CE17: E >= 35 y E < 45 y P >=25 y P<=30  --> Pr = 400
CE18: E >= 45 y E < 65 y P >=23 y P<=30  --> Pr =  250
CE19: E >=65 y E <=90 y P >=26 y P<=30  --> Pr =550
CE20: E >= 18 y E <25 y P > 0 y P<=28  --> Pr = 1400
CE21: E >= 25 y E < 35 y P > 0 y P<=26  --> Pr = 900
CE22: E >= 35 y E < 45 y P > 0 y P<=24  --> Pr = 500
CE23: E >= 45 y E < 65 y P > 0 y P<=22  --> Pr = 400
CE24: E >=65 y E <=90 y P > 0 y P<=25  --> Pr =750
CE25: Error
#### Tabla de valores límite (Entradas)
| Nº 	| Rango            | BLV | LV | ALV | BUV | UV | AUV |
| ---|------------------|-----|----|-----|-----|----|-----|
| 1 	| E < 18           | -   | -  | -   | 16  | 17 | 18  |
| 2 	| E >= 18 y E <25  | 17  | 18 | 19  | 23  | 24 | 25  |
| 3 	| E >= 25 y E < 35 | 24  | 25 | 26  | 33  | 34 | 35  |
| 4 	| E >= 35 y E < 45 | 34  | 35 | 36  | 43  | 44 | 45  |
| 5 	| E >= 45 y E < 65 | 44  | 45 | 46  | 63  | 64 | 65  |
| 6 	| E >=65 y E <=90  | 64  | 65 | 66  | 89  | 90 | 91  |
| 7 	| E > 90           | 90  | 91 | 92  | -   | -  | -   |
| 8 	| P < 1            | -   | -  | -   | -1  | 0  | 1   |
| 9 	| 1<=P<=30         | 0   | 1  | 2   | 29  | 30 | 31  |
| 10	| P > 30           | 30  | 31 | 32  | -   | -  | -   |

#### Tabla de valores límite (Salidas)
| Nº 	| Rango          | BLV | LV | ALV | BUV | UV | AUV |
| ---|----------------|-----|----|-----|-----|----|-----|
| 1 	|P >=29 y P<=30 | 28  | 29 | 30  | 29  | 30 | 31  |
| 2 	| P>=27 y P<=30  | 26  | 27 | 28  | 29  | 30 | 31  |
| 3 	| P >=25 y P<=30 | 24  | 25 | 26  | 29  | 30 | 31  |
| 4 	| P >=23 y P<=30 | 22  | 23 | 24  | 29  | 30 | 31  |
| 5 	| P >=26 y P<=30 | 25  | 26 | 27  | 29  | 30 | 31  |
| 6 	| P > 0 y P<=28  | 0   | 1  | 2   | 27  | 28 | 29  |
| 7 	| P > 0 y P<=26  | 0   | 1  | 2   | 25  | 26 | 27  |
| 8 	| P > 0 y P<=24  | 0   | 1  | 2   | 23  | 24 | 25  |
| 9 	| P > 0 y P<=22  | 0   | 1  | 2   | 21  | 22 | 23  |
| 10 	| P > 0 y P<=25  | 0   | 1  | 2   | 24  | 25 | 26  |

### Casos de prueba
| Nº Caso 	| Entrada E 	| Entrada P 	| Salida Prima 	| Clases Cubiertas                         	| Válido/Inválido 	|
|---------	|-----------	|-----------	|:------------:	|------------------------------------------	|-----------------	|
| CP1     	| 18        	| 30        	| 1350         	| CE1,CE4,CE10,CE14,AUVE1,LVE2,UVE9,BLVS10,ALVS1| V               	|
| CP2    	| 19        	| 29        	| 1350         	| CE1,CE4,CE10,CE14,CE15,ALVE2,LVS1,BUVS1,AUVS6 | V               	|
| CP3    	| 23        	| 28        	| 1400         	| CE1,CE4,CE10,CE14,CE20,BUVE2,BLVS1,UVS6      	| V               	|
| CP4    	| 20        	| 27         	| 1400         	| CE1,CE4,CE10,CE14,CE20,BUVS6		  	| V               	|
| CP5        	| 22         	| 2         	| 1400         	| CE1,CE4,CE10,CE14,CE20,ALVE9	   	   	| V               	|
| CP6    	| 24        	| 1         	| 1400         	| CE1,CE4,CE10,CE14,CE20,UVE2,BLVE3,AUVE8,LVE9	| V               	|
| CP7   	| 25        	| 26        	| 900        	| CE1,CE5,CE10,CE14,CE21,AUVE2,LVE3,BLVS2,UVS7  | V			|
| CP8    	| 26        	| 27        	| 850          	| CE1,CE5,CE10,CE14,CE16,ALVE3,LVS2,AUVS7 	| V               	|
| CP9    	| 33        	| 28        	| 850          	| CE1,CE5,CE10,CE14,CE16,BUVE3,ALVS2        	| V                	|
| CP10     	| 34        	| 25        	| 900          	| CE1,CE5,CE10,CE14,CE21,UVE3,BLVE4,BUVE9,BUVS7 | V                	|
| CP11     	| 35        	| 24        	| 500          	| CE1,CE6,CE10,CE14,CE22,AUVE3,LVE4,BLVS3,UVS8  | V                	|
| CP12     	| 36        	| 25        	| 400          	| CE1,CE6,CE10,CE14,CE17,ALVE4,LVS3,AUVS8 	| V                	|
| CP13    	| 43        	| 26        	| 400          	| CE1,CE6,CE10,CE14,CE17,BUVE4,ALVS3            | V                	|
| CP14    	| 44        	| 23        	| 500          	| CE1,CE6,CE10,CE14,CE22,UVE4,BLVE5,BUVS8 	| V                	|
| CP15    	| 45        	| 22          	| 400          	| CE1,CE7,CE10,CE14,CE23,AUVE4,LVE5,BLVS4,UVS9  | V                	|
| CP16    	| 46        	| 23        	| 250          	| CE1,CE7,CE10,CE14,CE18,ALVE5,LVS4,AUVS9      	| V                	|
| CP17    	| 63        	| 21        	| 400          	| CE1,CE7,CE10,CE14,CE23,BUVE5,BUVS9        	| V                	|
| CP18    	| 64        	| 24        	| 250          	| CE1,CE7,CE10,CE14,CE18,UVE5,BLVE6,ALVS4      	| V                	|
| CP19    	| 65        	| 25        	| 750          	| CE1,CE8,CE10,CE14,CE24,AUVE5,LVE6,BLVS5,UVS10 | V                	|
| CP20    	| 66        	| 26        	| 550          	| CE1,CE8,CE10,CE14,CE19,ALVE6,LVS5,AUVS10      | V                	|
| CP21    	| 89        	| 27        	| 550          	| CE1,CE8,CE10,CE14,CE19,BUVE6,ALVS5     	| V                	|
| CP22    	| 90        	| 24        	| 750          	| CE1,CE8,CE10,CE14,CE24,UVE6,BLVE7,BUVS10      | V                	|
| CP23    	| 16        	| 1        	| Error        	| CE1,CE3,CE10,CE14,CE25,BUVE1,LVE9		| I               	|
| CP24    	| 17        	| 30        	| Error        	| CE1,CE3,CE10,CE14,CE25,UVE1,BLVE2	 	| I               	|
| CP25    	| 91        	| 28        	| Error        	| CE1,CE9,CE10,CE14,CE25,AUVE6,LVE7           	| I                	|
| CP26    	| 92        	| 28        	| Error        	| CE1,CE9,CE10,CE14,CE25,ALVE7               	| I                	|
| CP27    	| 30        	| -1        	| Error        	| CE1,CE5,CE10,CE12,CE25,BUVE8	            	| I                	|
| CP28    	| 40        	| 0         	| Error        	| CE1,CE6,CE10,CE12,CE25,UVE8,BLVE9           	| I                	|
| CP29    	| 50        	| 31       	| Error        	| CE1,CE6,CE10,CE13,CE25,LVE10,AUVE9           	| I                	|
| CP30    	| 60        	| 32        	| Error        	| CE1,CE6,CE10,CE13,CE25,ALVE10               	| I                	|
| CP31    	| xyz       	| 28        	| Error        	| CE2,CE10,CE14,CE25                           	| I                	|
| CP32    	| 28       	| ábc        	| Error        	| CE1,CE5,CE11,CE25                          	| I                	|

### Implementación de los casos

Los casos válidos se probaron metiendo los valores en tres listas distintas y recorriendo por índice, comparando los valores de retorno de la funcion con los valores esperados en la lista Pr. Los casos inválidos se corrieron uno por uno, esperando la clase Exception para valores numericos y la clase Error cuando se trata de valores no numéricos. 
La prueba automatizada se puede observar en el commit (https://github.com/JorgePaladines/jenkins_taller_is2/commit/9be4683a935841be3a5f57bc4442fe8bbca38643)

La salida en la consola JUnit se puede apreciar que pasa todos los tests: 
![image](https://user-images.githubusercontent.com/29903640/72509343-651ba280-3815-11ea-8139-87ca6a565d1b.png)
Y además, en la consola se muestran los resultados para los casos válidos:
![image](https://user-images.githubusercontent.com/29903640/72509566-ce9bb100-3815-11ea-9443-149e2999e413.png)

 CP1
El valor es de 1350.0

 CP2
El valor es de 1350.0

 CP3
El valor es de 1400.0

 CP4
El valor es de 1400.0

 CP5
El valor es de 1400.0

 CP6
El valor es de 1400.0

 CP7
El valor es de 900.0

 CP8
El valor es de 850.0

 CP9
El valor es de 850.0

 CP10
El valor es de 900.0

 CP11
El valor es de 500.0

 CP12
El valor es de 400.0

 CP13
El valor es de 400.0

 CP14
El valor es de 500.0

 CP15
El valor es de 400.0

 CP16
El valor es de 250.0

 CP17
El valor es de 400.0

 CP18
El valor es de 250.0

 CP19
El valor es de 750.0

 CP20
El valor es de 550.0

 CP21
El valor es de 550.0

 CP22
El valor es de 750.0

#### Tabla de resultados
| Nº Caso 	| Entrada E 	| Entrada P 	| Salida Prima 	| Salida Consola	| Estado	|
|---------	|-----------	|-----------	|:------------:	|:-------------------:	|----------	|
| CP1     	| 18        	| 30        	| 1350         	| 1350         		| Aprobado	|
| CP2    	| 19        	| 29        	| 1350         	| 1350         		| Aprobado	|
| CP3    	| 23        	| 28        	| 1400         	| 1400         		| Aprobado	|
| CP4    	| 20        	| 27         	| 1400         	| 1400         		| Aprobado	|
| CP5        	| 22         	| 2         	| 1400         	| 1400         		| Aprobado	|
| CP6    	| 24        	| 1         	| 1400         	| 1400         		| Aprobado	|
| CP7   	| 25        	| 26        	| 900        	| 900         		| Aprobado	|
| CP8    	| 26        	| 27        	| 850          	| 850         		| Aprobado	|
| CP9    	| 33        	| 28        	| 850          	| 850         		| Aprobado	|
| CP10     	| 34        	| 25        	| 900          	| 900         		| Aprobado	|
| CP11     	| 35        	| 24        	| 500          	| 500         		| Aprobado	|
| CP12     	| 36        	| 25        	| 400          	| 400         		| Aprobado	|
| CP13    	| 43        	| 26        	| 400          	| 400         		| Aprobado	|
| CP14    	| 44        	| 23        	| 500          	| 500         		| Aprobado	|
| CP15    	| 45        	| 22          	| 400          	| 400         		| Aprobado	|
| CP16    	| 46        	| 23        	| 250          	| 250         		| Aprobado	|
| CP17    	| 63        	| 21        	| 400          	| 400         		| Aprobado	|
| CP18    	| 64        	| 24        	| 250          	| 250         		| Aprobado	|
| CP19    	| 65        	| 25        	| 750          	| 750         		| Aprobado	|
| CP20    	| 66        	| 26        	| 550          	| 550         		| Aprobado	|
| CP21    	| 89        	| 27        	| 550          	| 550         		| Aprobado	|
| CP22    	| 90        	| 24        	| 750          	| 750         		| Aprobado	|
| CP23    	| 16        	| 1        	| Error        	| Error        		| Aprobado	|
| CP24    	| 17        	| 30        	| Error        	| Error        		| Aprobado	|
| CP25    	| 91        	| 28        	| Error        	| Error        		| Aprobado	|
| CP26    	| 92        	| 28        	| Error        	| Error        		| Aprobado	|
| CP27    	| 30        	| -1        	| Error        	| Error        		| Aprobado	|
| CP28    	| 40        	| 0         	| Error        	| Error        		| Aprobado	|
| CP29    	| 50        	| 31       	| Error        	| Error        		| Aprobado	|
| CP30    	| 60        	| 32        	| Error        	| Error        		| Aprobado	|
| CP31    	| xyz       	| 28        	| Error        	| Error        		| Aprobado	|
| CP32    	| 28       	| ábc        	| Error        	| Error        		| Aprobado	|

### Estado de prueba del sistema: Todos los casos aprobados.

## **Pruebas de Integración**

### _Solo existe un módulo, por lo que no es necesario revisar la integración entre componentes._ 
#### Estado de pruebas de integración: Módulo único.

**Comment by mianmuri1991** [comment]
**ETAPA 8: REALIZAR PRUEBAS DE ACEPTACIÓN CON QUIEN HA CREADO EL INCIDENTE**

Al realizar las pruebas de aceptación luego de la corrección del código se observa que efectivamente, el cálculo de la prima para la edad de 65 o más permite la reducción de hasta 4 puntos.

Se realizan 3 pruebas de aceptación, todas referentes al cambio realizado. Se puede observar que solo cuando el numero de puntos perdidos es 26 se aplica la reducción. 

![image](https://user-images.githubusercontent.com/43896261/72529901-382eb600-383c-11ea-84d1-e40672f41796.png)

**Comment by dcmonten** [comment]
@cmonsalvec el incidente ha sido corregido, ¿esta usted de acuerdo con la corrección realizada?

**Comment by cmonsalvec** [comment]
Muchas gracias, estoy satisfecho con la solución dada. Pueden proceder con el cierre del ticket.

**Comment by dcmonten** [comment]
# Verificación de completitud

## Etapas
1. Reporte del incidente - REVISADO
2. Reproducción del problema - HECHO
3. Categorización del incidente - HECHO
4. Asignaciones - HECHO
5. Análisis de impacto - HECHO
6. Solución del incidente - HECHO
7. Pruebas de sistema e integración - APROBADAS
8. Pruebas de aceptación - APROBADAS

## Incidente resuelto
